version: '3'

services:
  frontend-compose:
    image: frontend-compose
    build:
      context: ../frontend-example-docker
    ports:
      - 5000:5000
    container_name: frontend-compose
  backend-compose:
    image: backend-compose
    build:
      context: ../backend-example-docker
    ports:
      - 8000:8000
    environment:
      - REDIS=database
      - REDIS_PORT=6379
    container_name: backend-compose
  database:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
