FROM alpine:3.10

ENV PATH /root/.rbenv/bin:/root/.rbenv/shims/:$PATH

# Install packages for building ruby
RUN apk add --no-cache --update build-base bash linux-headers git sqlite-dev nodejs tzdata \
                     openssl-dev readline-dev zlib-dev && \
    rm -rf /var/cache/apk/* && \
# Install rbenv and ruby-build
    git clone https://github.com/rbenv/rbenv.git /root/.rbenv && \
    git clone https://github.com/rbenv/ruby-build.git /root/.rbenv/plugins/ruby-build  && \
    /root/.rbenv/plugins/ruby-build/install.sh  && \
    echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh && \
    echo 'eval "$(rbenv init -)"' >> /root/.bashrc && \
# Install version 2.6.0 of ruby
    rbenv install 2.6.0 && \
    rbenv global 2.6.0 && \
    echo 'gem: --no-rdoc --no-ri' >> /root/.gemrc && \
    gem environment --config-file /root/.gemrc

# Add new a user
WORKDIR /app
RUN adduser -D app && \
    chown -R app /app && \
    chmod -R a+wxr /root && \
    chmod -R u+xwr /root/.rbenv
USER app

COPY . ./

# Install gems
ENV BUNDLE_SILENCE_ROOT_WARNING 1
RUN gem install bundler && \
    bundle install && \
    rbenv rehash
# Rails
RUN bin/rails db:migrate

EXPOSE 3000

CMD ["rails", "s"]
