FROM ubuntu:16.04 as build-stage

RUN apt-get update && \
    apt-get -y install openjdk-8-jdk curl && \
    rm -rf /var/lib/apt/lists/*

ENV MAVEN_HOME /usr/share/maven

RUN curl -fsSL http://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz | tar xzf - -C /usr/share && \
    mv /usr/share/apache-maven-3.6.3 /usr/share/maven && \
    ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

WORKDIR /apps

COPY . /apps

RUN mvn package

FROM alpine:3.10

WORKDIR /apps

COPY --from=build-stage /apps/target/ /apps

RUN apk add --no-cache --update bash openjdk8-jre && \
    rm -rf /var/cache/apk/* && adduser -D app

EXPOSE 8080

USER app
CMD ["/usr/bin/java", "-jar", "./MyApp-1.0-SNAPSHOT.jar"]
