version: '3'

services:
  frontend-compose:
    image: frontend-compose
    build:
      context: ../frontend-example-docker
    ports:
      - 5000:5000
    container_name: frontend-compose
  backend-compose:
    image: backend-compose
    build:
      context: ../backend-example-docker
    ports:
      - 8000:8000
    environment:
      - REDIS=cache
      - REDIS_PORT=6379
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=postgres_db
      - DB_HOST=postgres
    container_name: backend-compose
  cache:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    container_name: redis
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db
